### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Ciaran0** [Tapad/sbt-docker-compose#2]
Hi,
do you have any idea why i am getting this error?

`Creating Local Docker Compose Environment.
Reading Compose File: /home/cioconnor/development/risk/docker/docker-compose.yml
java.lang.NullPointerException
	at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$2.<init>(Wrappers.scala:265)
	at scala.collection.convert.Wrappers$JMapWrapperLike$class.iterator(Wrappers.scala:264)
	at scala.collection.convert.Wrappers$JMapWrapper.iterator(Wrappers.scala:275)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:263)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
	at com.tapad.docker.ComposeFile$class.getPortInfo(ComposeFile.scala:107)
	at com.tapad.docker.DockerComposePluginLocal.getPortInfo(DockerComposePlugin.scala:70)
	at com.tapad.docker.ComposeFile$$anonfun$processCustomTags$1.apply(ComposeFile.scala:63)
	at com.tapad.docker.ComposeFile$$anonfun$processCustomTags$1.apply(ComposeFile.scala:45)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.tapad.docker.ComposeFile$class.processCustomTags(ComposeFile.scala:45)
	at com.tapad.docker.DockerComposePluginLocal.processCustomTags(DockerComposePlugin.scala:70)
	at com.tapad.docker.DockerComposePluginLocal.startDockerCompose(DockerComposePlugin.scala:150)
	at com.tapad.docker.DockerComposePluginLocal.launchInstanceWithLatestChanges(DockerComposePlugin.scala:114)
	at com.tapad.docker.DockerComposePluginLocal$$anonfun$dockerComposeUpCommand$1.apply(DockerComposePlugin.scala:80)
	at com.tapad.docker.DockerComposePluginLocal$$anonfun$dockerComposeUpCommand$1.apply(DockerComposePlugin.scala:78)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:70)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
`

Thanks

**Comment by kurtkopchik** [comment]
Where you able to figure out what the issue was?

**Comment by Ciaran0** [comment]
Hi @kurtkopchik thanks for the message.
Yeah it was a stupid mistake, error is a bit ambiguous.

I am now stuck trying to get docker compose to pick up a local image. 
`cassandra:
  image: cassandra:latest
  ports:
    - "7000:7000"
    - "7001:7001"
    - "9042:9042"
    - "7199:7199"
app:
  image: app:0.1<localBuild>
  ports:
    - "8080:8080"
  links:
    - "cassandra"`

I am getting the error
`java.io.IOException: Cannot run program "docker-compose": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
`

**Comment by kurtkopchik** [comment]
Do you have the full output from "dockerComposeUp"? From the error message you pasted it sounds like the "docker-compose" command is not being found when run from the plugin. If you type "docker-compose" on the command line from the shell where you are running sbt the executable is it found?
